### ISSUE TITLE
Qtractor does not open

### ISSUE THREAD

**Issue by marco4mp** [flathub/org.rncbc.qtractor#46]
Hi, I just installed Qtractor and it doesn't open.
When opening from the Terminal (flatpak run org.rncbc.qtractor) it gives the following message :

`qtractor.bin: symbol lookup error: qtractor.bin: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6`

Ubuntu 23.10

**Comment by hfiguiere** [comment]
I have the same here. I wonder if that's not a binary breakage that happened recently with he Sdk.

**Comment by hfiguiere** [comment]
I'll trigger a rebuild, as a local build works.

**Comment by hfiguiere** [comment]
Update the flatpak and it should work. The new build is available and works here.

**Comment by marco4mp** [comment]
Thank you! Now it works.
