### ISSUE TITLE
This package should mount user .vst3 directory

### ISSUE THREAD

**Issue by peerchemist** [flathub/org.rncbc.qtractor#7]
Quite a few DAWs already respect user VST_PATH, VST3_PATH, and LV2_PATH.

```
$HOME/.vst
$HOME/.vst3
```

**Comment by hfiguiere** [comment]
not sure what you mean by "mounted", but the whole `$HOME` is available by default.

**Comment by hfiguiere** [comment]
this should work now.

**Comment by peerchemist** [comment]
Yes, that is it, thanks!
